name:                cmple
version:             0.1.0.0
github:              "nikos-alexandris/cmple"
license:             BSD3
author:              "Nikos Alexandris"
maintainer:          "nikos-alexandris@protonmail.com"
copyright:           "2023 Nikos Alexandris"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cmple#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- toml-reader
- directory
- dir-traverse
- process
- deepseq
- zip
- wreq
- http-client
- bytestring
- text
- lens

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cmple:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmple

tests:
  cmple-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmple
